# Generated by Django 4.1.3 on 2023-01-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_is_active_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('EMPLOYEE', 'Employee')], default='CUSTOMER', max_length=50),
        ),
    ]
