# Generated by Django 4.1.3 on 2023-01-10 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Franchise', '0001_initial'),
        ('account', '0004_remove_employee_facbook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_img', models.ImageField(default='media/empimg/AviDP.jpeg', upload_to='media/empimg')),
                ('is_active', models.BooleanField(default=False)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Franchise.center')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
