# Generated by Django 4.1.3 on 2023-02-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_employee_emp_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employeeadmin',
            name='is_active',
        ),
    ]
