# Generated by Django 4.1.3 on 2023-02-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_customer_is_active_remove_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('EMPLOYEE', 'Employee'), ('HR', 'Human Resource Manager'), ('SM', 'Service Manager'), ('SA', 'Service Advisor'), ('NA', 'NA'), ('BSM', 'Body Shop Manager'), ('BSA', 'Body Shop Advisor'), ('CRM', 'Customer Relationship Manager'), ('SPM', 'Spare Part Manager'), ('SPE', 'Spare Part Executive'), ('AM', 'Account Manager')], default='CUSTOMER', max_length=50),
        ),
        migrations.DeleteModel(
            name='EmployeeAdmin',
        ),
    ]
