# Generated by Django 4.1.3 on 2023-01-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='Diam dolor diam ipsum sit amet diam et eos erat ipsum', max_length=400)),
                ('duration', models.DurationField()),
                ('renew_time', models.DurationField()),
                ('price', models.IntegerField(default=500)),
                ('on_display', models.BooleanField(default=False)),
                ('icon', models.CharField(default='fa fa-certificate fa-3x text-primary flex-shrink-0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_time', models.DurationField()),
                ('service_date', models.DateTimeField()),
                ('service_estimate', models.FloatField(default=100)),
                ('progress', models.CharField(choices=[('RO Open', 'RO Open'), ('Step 2', 'Step 2'), ('Step 3', 'Step 3')], default='Step 1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_image', models.ImageField(blank=True, null=True, upload_to='media/updateimg')),
                ('update_title', models.CharField(blank=True, max_length=50, null=True)),
                ('update_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
