# Generated by Django 4.1.3 on 2022-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providedservice',
            name='duration',
            field=models.DateField(),
        ),
    ]
