# Generated by Django 4.1.3 on 2023-01-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Franchise', '0001_initial'),
        ('ERP', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehical',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
        migrations.AddField(
            model_name='update',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Franchise.center'),
        ),
        migrations.AddField(
            model_name='service',
            name='services',
            field=models.ManyToManyField(to='ERP.providedservice'),
        ),
        migrations.AddField(
            model_name='service',
            name='vehical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.vehical'),
        ),
    ]
