# Generated by Django 4.1.3 on 2023-01-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_is_active_employee_is_active'),
        ('ERP', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehical',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer'),
        ),
    ]
