# Generated by Django 4.1.3 on 2023-01-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_alter_vehical_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehical',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
