# Generated by Django 4.1.3 on 2022-11-25 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_employee_center_remove_employee_job_role_and_more'),
        ('ERP', '0003_alter_providedservice_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_time', models.DurationField()),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.center')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.customer')),
                ('services', models.ManyToManyField(to='ERP.providedservice')),
                ('vehical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.vehical')),
            ],
        ),
    ]
