# Generated by Django 4.1.3 on 2023-01-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_alter_vehical_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='additional_services',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='additional_services_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
