# Generated by Django 4.1.3 on 2023-01-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_service_additional_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_time',
        ),
    ]
