# Generated by Django 4.1.3 on 2022-11-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0005_delete_jobrole_alter_service_center_delete_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customer',
        ),
    ]
