# Generated by Django 4.1.3 on 2022-11-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_service_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='progress',
            field=models.CharField(choices=[('Step 1', 'Step 1'), ('Step 2', 'Step 2'), ('Step 3', 'Step 3')], default='Step 1', max_length=20),
        ),
    ]
