# Generated by Django 4.1.3 on 2023-01-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_service_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='additional_services_cost',
        ),
    ]
