# Generated by Django 4.1.3 on 2023-01-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_remove_service_additional_services_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='progress',
            field=models.CharField(choices=[('WAITING', 'WAITING')], default='WAITING', max_length=20),
        ),
    ]
