# Generated by Django 4.1.3 on 2022-11-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_service_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='providedservice',
            name='price',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='progress',
            field=models.CharField(choices=[('RO Open', 'RO Open'), ('Step 2', 'Step 2'), ('Step 3', 'Step 3')], default='Step 1', max_length=20),
        ),
    ]
