# Generated by Django 4.1.3 on 2023-02-13 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('ERP', '0009_alter_payslip_slip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT MARKED', 'NOT MARKED'), ('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT')], default='NOT MARKED', max_length=50)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
