# Generated by Django 4.1.3 on 2023-03-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('NA', 'NA'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('DONE', 'DONE'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='NA', max_length=50)),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.service')),
            ],
        ),
    ]
