# Generated by Django 4.1.3 on 2023-02-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Franchise', '0006_center_location'),
        ('ERP', '0010_alter_service_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providedservice',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='providedservice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='providedservice',
            name='renew_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='services',
        ),
        migrations.CreateModel(
            name='CenterServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='Diam dolor diam ipsum sit amet diam et eos erat ipsum', max_length=400)),
                ('price', models.IntegerField(default=500)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Franchise.center')),
            ],
        ),
    ]
