# Generated by Django 4.1.3 on 2023-02-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0011_remove_providedservice_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProvidedService',
        ),
        migrations.AddField(
            model_name='service',
            name='additional_services_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='services',
            field=models.ManyToManyField(to='ERP.centerservices'),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional_services',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_estimate',
            field=models.CharField(default='1000', max_length=10),
        ),
    ]
