# Generated by Django 4.1.3 on 2023-03-05 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('ERP', '0011_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.employee'),
            preserve_default=False,
        ),
    ]
