# Generated by Django 4.1.3 on 2023-02-01 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Franchise', '0006_center_location'),
        ('ERP', '0012_delete_providedservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Franchise.center'),
        ),
    ]
