# Generated by Django 4.1.3 on 2023-02-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Franchise', '0006_center_location'),
        ('ERP', '0013_alter_service_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_estimate',
        ),
        migrations.AlterField(
            model_name='service',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Franchise.center'),
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ERP.service')),
            ],
        ),
    ]
