# Generated by Django 4.1.3 on 2023-03-05 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Franchise', '0001_initial'),
        ('ERP', '0013_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='center',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Franchise.center'),
            preserve_default=False,
        ),
    ]
