# Generated by Django 4.1.3 on 2023-02-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0014_remove_service_service_estimate_alter_service_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerservices',
            name='tax',
            field=models.FloatField(default=5),
        ),
    ]
