# Generated by Django 4.1.3 on 2023-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0015_alter_task_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='serial_number',
            field=models.CharField(default='sno', max_length=50),
            preserve_default=False,
        ),
    ]
