# Generated by Django 4.1.3 on 2023-02-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0017_estimate_created_at_alter_estimate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehical',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehical',
            name='number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
