# Generated by Django 4.1.3 on 2023-03-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0019_centerproduct_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='additional_services',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
