# Generated by Django 4.1.3 on 2023-03-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0020_alter_service_additional_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.centerproduct')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.service')),
            ],
            options={
                'unique_together': {('service', 'product')},
            },
        ),
    ]
