# Generated by Django 4.1.3 on 2023-05-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0021_productsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
