# Generated by Django 4.1.3 on 2023-03-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Franchise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
