# Generated by Django 4.1.3 on 2023-01-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Franchise', '0003_remove_center_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
