# Generated by Django 4.1.3 on 2023-01-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Franchise', '0005_remove_center_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Franchise.location'),
        ),
    ]
