# Generated by Django 4.1.3 on 2023-01-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ProvidedServices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.providedservice'),
        ),
    ]
