# Generated by Django 4.1.3 on 2022-12-10 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_providedservice_price_alter_service_progress'),
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='services',
        ),
        migrations.AddField(
            model_name='booking',
            name='ProvidedServices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.providedservice'),
        ),
    ]
