# Generated by Django 4.1.3 on 2023-01-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarasouleElement',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='content',
            new_name='issue',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ProvidedServices',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehical',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
