# Generated by Django 4.1.3 on 2022-12-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_employee_emp_img'),
        ('Base', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('employees', models.ManyToManyField(to='account.employee')),
            ],
        ),
    ]
