# Generated by Django 4.1.3 on 2022-12-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_employeedisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedisplay',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
