# Generated by Django 4.1.3 on 2023-02-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_remove_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehical',
        ),
    ]
