# Generated by Django 4.1.3 on 2023-02-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_remove_booking_email_remove_booking_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/brands/logos')),
                ('name', models.TextField(max_length=50)),
                ('has_two_wheeler', models.BooleanField(default=True)),
                ('has_four_wheeler', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='VechicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fule_type', models.TextField(choices=[('PETROL', 'PETROL'), ('DIESEL', 'DIESEL'), ('CNG', 'CNG')], max_length=50)),
                ('name', models.TextField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.brand')),
            ],
        ),
    ]
