# Generated by Django 4.1.3 on 2023-02-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_brand_alter_booking_phone_vechicalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.brand')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='fule_type',
            field=models.CharField(default=' Petrol', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VechicalModel',
        ),
    ]
