# Generated by Django 4.1.3 on 2022-12-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_employee_emp_img'),
        ('Base', '0006_remove_employeedisplay_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedisplay',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee'),
        ),
    ]
