# Generated by Django 4.1.3 on 2022-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_employee_emp_img'),
        ('Base', '0007_alter_employeedisplay_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedisplay',
            name='employees',
        ),
        migrations.AddField(
            model_name='employeedisplay',
            name='employees',
            field=models.ManyToManyField(to='account.employee'),
        ),
    ]
