# Generated by Django 4.1.3 on 2023-02-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_vehicalmodel_booking_fule_type_delete_vechicalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.vehicalmodel'),
        ),
        migrations.AlterField(
            model_name='vehicalmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='Base.brand'),
        ),
    ]
