# Generated by Django 4.1.3 on 2022-12-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_remove_employeedisplay_employees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDisplay',
        ),
    ]
