# Generated by Django 4.1.3 on 2022-12-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_delete_employeedisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(default='media/testimg/AviDP.jpeg', upload_to='media/testimg')),
            ],
        ),
    ]
