# Generated by Django 4.1.3 on 2022-12-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_testimonial_on_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarasouleElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_img', models.ImageField(upload_to='media/carasouleimg')),
                ('on_display', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
