# Generated by Django 4.1.3 on 2022-12-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_carasouleelement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carasouleelement',
            old_name='emp_img',
            new_name='img',
        ),
    ]
